version: "2"
services:
  zookeeper:
    image: 'zookeeper:3.4'
    hostname: zookeeper
  admin:
    image: 'chenchuxin/dubbo-admin:latest'
    environment: 
      - dubbo.registry.address=zookeeper://zookeeper:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=root
    ports: 
      - "8080:8080"
  producer:
    image: 'binblee/producer:0.1'
    build: 
      dockerfile: Dockerfile
      context: ./service-producer/
    environment:
      - ZOOKEEPER_SERVER=zookeeper
  consumer:
    image: 'binblee/consumer:0.1'
    build: 
      dockerfile: Dockerfile
      context: ./service-consumer/
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - SERVER_PORT=8899
      - DUBBO_IP_TO_REGISTRY=10.8.0.34
    ports:
      - 8899:8899
